const answer = {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 2,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 32,
    healthScore: 44,
    creditsText: "Lisa's Vegetarian Kitchen",
    license: 'CC BY 2.5 CA',
    sourceName: 'Food and Spice',
    pricePerServing: 36.59,
    id: 792072,
    title: 'Dressed Up Kale Salad',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://foodandspice.blogspot.com/2016/06/dressed-up-kale-salad.html',
    image: 'https://spoonacular.com/recipeImages/792072-312x231.jpg',
    imageType: 'jpg',
    summary: 'Need a <b>gluten free and vegan side dish</b>? Dressed Up Kale Salad could be a tremendous recipe to try. This recipe makes 4 servings with <b>63 calories</b>, <b>3g of protein</b>, and <b>2g of fat</b> each. For <b>37 cents per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. This recipe is liked by 31 foodies and cooks. If you have agave nectar, tahini, water, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 95%</b>. This score is amazing. Try 
  <a href="https://spoonacular.com/recipes/all-dressed-kale-chips-470434">All-Dressed Kale Chips</a>, <a href="https://spoonacular.com/recipes/spinach-kale-soup-with-tahini-dressed-chickpeas-15325">Spinach & Kale Soup With Tahini Dressed Chickpeas</a>, and <a href="https://spoonacular.com/recipes/warm-bacon-dressed-zucchini-noodles-with-mushrooms-kale-and-a-fried-egg-563781">Warm Bacon Dressed Zucchini Noodles with Mushrooms, Kale and a Fried Egg</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'salad' ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/dressed-up-kale-salad-792072'
  }
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 5,
    healthScore: 87,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 184.55,
    id: 632269,
    title: 'Amaranth and Roast Veggie Salad',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: 'http://www.foodista.com/recipe/BPXZ2RCY/amaranth-and-roast-veggie-salad',
    image: 'https://spoonacular.com/recipeImages/632269-312x231.jpg',
    imageType: 'jpg',
    summary: `Amaranth and Roast Veggie Salad might be just the side dish you are searching for. This recipe makes 2 servings with <b>331 calories</b>, <b>7g of protein</b>, and <b>18g of fat</b> each. For <b>$1.47 per serving</b>, this recipe <b>covers 15%</b> of your 
  daily requirements of vitamins and minerals. Only a few people made this recipe, and 5 would say it hit the spot. From preparation to 
  the plate, this recipe takes roughly <b>45 minutes</b>. Head to the store and pick up onion, punnet baby tomatoes, pepper, and a few other things to make it today. It is a good option if you're following a <b>gluten free and vegan</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 87%</b>. This score is tremendous. Try <a href="https://spoonacular.com/recipes/mums-roast-veggie-salad-12573">Mum’s Roast Veggie Salad</a>, <a href="https://spoonacular.com/recipes/amaranth-yogurt-parfait-popped-amaranth-parfait-with-fruits-486629">amaranth yogurt parfait – popped amaranth parfait with fruits</a>, and <a href="https://spoonacular.com/recipes/coriander-cauliflower-amaranth-salad-882971">Coriander Cauliflower Amaranth Salad</a> for similar recipes.`,
    cuisines: [],
    dishTypes: [ 'side dish' ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/amaranth-and-roast-veggie-salad-632269'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 9,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 4,
    healthScore: 100,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 450.04,
    id: 659143,
    title: 'Salmon, Watercress, Fennel and Baby Beetroot Salad With Lemony "Caviar" Dressing',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.foodista.com/recipe/WHSTLX2T/salmon-watercress-fennel-and-baby-beetroot-salad-with-lemony-arenkha-msc-dressing',
    image: 'https://spoonacular.com/recipeImages/659143-312x231.jpg',
    imageType: 'jpg',
    summary: 'You can never have too many main course recipes, so give Salmon, Watercress, Fennel and Baby Beetroot Salad With Lemony "Caviar" Dressing a try. This caveman, gluten free, dairy free, and primal recipe serves 4 and costs <b>$4.13 per serving</b>. One serving contains <b>433 calories</b>, <b>27g of protein</b>, and <b>29g of fat</b>. If you have baby beets, bay leaf, pepper, and a few other ingredients on hand, you can make it. Only a few people made this recipe, and 4 would say it hit the spot. From preparation to the 
  plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 93%</b>. This score is great. Try <a href="https://spoonacular.com/recipes/-wild-rice-baby-beetroot-beef-kofta-salad-ft-love-beets-baby-beetroot-494268">[] Wild Rice, Baby Beetroot & Beef Kofta Salad (ft. Love Beets Baby Beetroot)</a>, <a href="https://spoonacular.com/recipes/poached-salmon-and-watercress-salad-with-dill-yogurt-dressing-14170">Poached Salmon and Watercress Salad with Dill-Yogurt Dressing</a>, and <a href="https://spoonacular.com/recipes/beetroot-red-apple-and-watercress-salad-9732">Beetroot, Red Apple And Watercress Salad</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [
      'gluten free',
      'dairy free',
      'paleolithic',
      'primal',
      'pescatarian'
    ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/salmon-watercress-fennel-and-baby-beetroot-salad-with-lemony-caviar-dressing-659143' 
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 13,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 400,
    healthScore: 36,
    creditsText: 'Jen West',
    sourceName: 'Pink When',
    pricePerServing: 420.62,
    id: 715533,
    title: 'Filet Mignon Soft Tacos',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: 'http://www.pinkwhen.com/filet-mignon-soft-tacos-recipe/',
    image: 'https://spoonacular.com/recipeImages/715533-312x231.jpg',
    imageType: 'jpg',
    summary: 'The recipe Filet Mignon Soft Tacos could satisfy your Mexican craving in approximately <b>45 minutes</b>. This main course has <b>512 calories</b>, <b>50g of protein</b>, and <b>29g of fat</b> per serving. For <b>$4.21 per serving</b>, this recipe <b>covers 24%</b> of your daily requirements of vitamins and minerals. If you have cream, extra virgin olive oil, cracked pepper, and a few other ingredients on hand, you can make it. To use up the extra virgin olive oil you could follow this main course with the <a href="https://spoonacular.com/recipes/peach-crisp-healthy-crisp-for-breakfast-487698">Peach Crisp: Healthy Crisp for Breakfast</a> as a dessert. 400 people were impressed by this recipe. All things considered, we decided this recipe <b>deserves a spoonacular score of 95%</b>. 
  This score is super. Similar recipes include <a href="https://spoonacular.com/recipes/filet-mignon-81371">Filet Mignon</a>, <a href="https://spoonacular.com/recipes/filet-mignon-593891">Filet Mignon</a>, and <a href="https://spoonacular.com/recipes/filet-mignon-pasta-702027">Filet Mignon Pasta</a>.',
    cuisines: [ 'Mexican' ],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'gluten free', 'pescatarian' ],
    occasions: [],
    analyzedInstructions: [],
    spoonacularSourceUrl: 'https://spoonacular.com/filet-mignon-soft-tacos-715533'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 7,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 18,
    healthScore: 78,
    creditsText: 'foodista.com',
    sourceName: 'foodista.com',
    pricePerServing: 357.85,
    id: 640921,
    title: 'Stuffed Artichoke Main Dish',
    readyInMinutes: 60,
    servings: 2,
    sourceUrl: 'http://www.foodista.com/recipe/X8NMGGCS/crown-chokes',
    image: 'https://spoonacular.com/recipeImages/640921-312x231.jpg',
    imageType: 'jpg',
    summary: 'Need a <b>gluten free main course</b>? Stuffed Artichoke Main Dish could be a super recipe to try. For <b>$2.1 per serving</b>, this recipe <b>covers 26%</b> of your daily requirements of vitamins and minerals. This recipe makes 2 servings with <b>272 calories</b>, <b>30g of protein</b>, and <b>6g of fat</b> each. 18 people were impressed by this recipe. If you have potato, chicken breasts, salt, and a few other ingredients on hand, you can make it. To use up the olive oil you could follow this main course with the <a 
  href="https://spoonacular.com/recipes/sauteed-banana-granola-and-yogurt-parfait-624619">Sauteed Banana, Granolan and Yogurt Parfait</a> as a dessert. From preparation to the plate, this recipe takes about <b>1 hour</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 85%</b>. This score is awesome. Try <a href="https://spoonacular.com/recipes/caprese-style-stuffed-main-dish-636963">Caprese-Style Stuffed Main Dish</a>, <a href="https://spoonacular.com/recipes/main-dish-minestrone-167120">Main-Dish Minestrone</a>, and <a href="https://spoonacular.com/recipes/summertime-main-dish-salad-401103">Summertime Main-Dish Salad</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'gluten free' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/stuffed-artichoke-main-dish-640921'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 9,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 19,
    healthScore: 67,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 874.74,
    id: 639411,
    title: 'Cilantro Lime Halibut',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: 'http://www.foodista.com/recipe/W2C6K48J/cilantro-lime-halibut',
    image: 'https://spoonacular.com/recipeImages/639411-312x231.jpg',
    imageType: 'jpg',
    summary: 'Cilantro Lime Halibut is a <b>caveman, gluten free, dairy free, and primal</b> main course. For <b>$8.75 per serving</b>, 
  this recipe <b>covers 28%</b> of your daily requirements of vitamins and minerals. One serving contains <b>418 calories</b>, <b>43g of protein</b>, and <b>22g of fat</b>. 19 people were impressed by this recipe. From preparation to the plate, this recipe takes around 
  <b>45 minutes</b>. If you have juice of lime, another slug of blood orange olive oil, dusting of garlic-pepper, and a few other ingredients on hand, you can make it. To use up the white wine you could follow this main course with the <a href="https://spoonacular.com/recipes/white-wine-frozen-yogurt-206235">White Wine Frozen Yogurt</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 95%</b>. This score is great. Try <a href="https://spoonacular.com/recipes/halibut-with-citrus-and-cilantro-3296">Halibut With Citrus And Cilantro</a>, <a href="https://spoonacular.com/recipes/cilantro-ginger-halibut-86400">Cilantro-Ginger Halibut</a>, and <a href="https://spoonacular.com/recipes/poached-halibut-with-ginger-and-cilantro-3349">Poached Halibut with Ginger and Cilantro</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [
      'gluten free',
      'dairy free',
      'paleolithic',
      'primal',
      'pescatarian'
    ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/cilantro-lime-halibut-639411'
  }
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 12,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3,
    healthScore: 100,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 252.69,
    id: 646043,
    title: 'Gujarati Dry Mung Bean Curry',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.foodista.com/recipe/G6ZJW56S/gujarati-dry-mung-bean-curry',
    image: 'https://spoonacular.com/recipeImages/646043-312x231.jpg',
    imageType: 'jpg',
    summary: `The recipe Gujarati Dry Mung Bean Curry is ready <b>in around 45 minutes</b> and is definitely an excellent <b>gluten free and vegan</b> option for lovers of Indian food. For <b>$2.53 per serving</b>, this recipe <b>covers 45%</b> of your daily requirements of vitamins and minerals. This recipe makes 4 servings with <b>417 calories</b>, <b>23g of protein</b>, and <b>6g of fat</b> each. This recipe from Foodista has 2 fans. It works well as an affordable main course. A mixture of salt, sugar, cinnamon powder, and a handful of other ingredients are all it takes to make this recipe so flavorful. To use up the cumin seeds you could follow this main course with the <a href="https://spoonacular.com/recipes/indian-fried-banana-cakes-mangalore-buns-899949">Indian Fried Banana Cakes (Mangalore Buns)</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 94%</b>. This score is amazing. Try <a href="https://spoonacular.com/recipes/uncle-bills-mung-bean-curry-113139">Uncle Bill's Mung Bean Curry</a>, <a href="https://spoonacular.com/recipes/mung-bean-crepes-34435">Mung Bean Crepes</a>, and <a href="https://spoonacular.com/recipes/korean-mung-with-bean-34423">Korean Mung With Bean</a> for similar recipes.`,
    cuisines: [ 'Indian', 'Asian' ],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/gujarati-dry-mung-bean-curry-646043'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 6,
    gaps: 'no',
    preparationMinutes: 5,
    cookingMinutes: 20,
    aggregateLikes: 6,
    healthScore: 83,
    creditsText: 'Jen West',
    sourceName: 'Pink When',
    pricePerServing: 271.9,
    id: 975070,
    title: 'Instant Pot Chicken Taco Soup',
    readyInMinutes: 25,
    servings: 4,
    sourceUrl: 'http://www.pinkwhen.com/instant-pot-chicken-taco-soup/',
    image: 'https://spoonacular.com/recipeImages/975070-312x231.jpg',
    imageType: 'jpg',
    summary: 'Need a <b>gluten free and dairy free main course</b>? Instant Pot Chicken Taco Soup could be a great recipe to try. One serving contains <b>346 calories</b>, <b>25g of protein</b>, and <b>8g of fat</b>. This recipe serves 4. For <b>$2.72 per serving</b>, this recipe <b>covers 40%</b> of your daily requirements of vitamins and minerals. 6 people have made this recipe and would make it again. This recipe is typical of Mexican cuisine. Head to the store and pick up chili powder, green onion, canned tomatoes, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>25 minutes</b>. It is perfect for <b>Autumn</b>. It is brought to you by Pink When. Taking all factors into account, this recipe <b>earns a spoonacular score of 99%</b>, which is spectacular. Similar recipes are <a href="https://spoonacular.com/recipes/instant-pot-chicken-taco-soup-944691">Instant Pot Chicken Taco Soup</a>, <a href="https://spoonacular.com/recipes/instant-pot-taco-soup-937475">Instant Pot Taco Soup</a>, and <a href="https://spoonacular.com/recipes/instant-pot-taco-soup-953509">Instant Pot Taco Soup</a>.',
    cuisines: [ 'Mexican' ],
    dishTypes: [ 'soup' ],
    diets: [ 'gluten free', 'dairy free' ],
    occasions: [ 'fall', 'winter' ],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/instant-pot-chicken-taco-soup-975070'
  }
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 12,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3,
    healthScore: 100,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 254.65,
    id: 636608,
    title: 'Butternut Squash, Arugula and Goat Cheese Quinoa',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/CB6CM523/butternut-squash-arugula-and-goat-cheese-quinoa',
    image: 'https://spoonacular.com/recipeImages/636608-312x231.jpg',
    imageType: 'jpg',
    summary: 'Butternut Squash, Arugulan and Goat Cheese Quinoan is a <b>gluten free and lacto ovo vegetarian</b> recipe with 4 servings. One serving contains <b>482 calories</b>, <b>15g of protein</b>, and <b>23g of fat</b>. For <b>$2.55 per serving</b>, this recipe <b>covers 31%</b> of your daily requirements of vitamins and minerals. 3 people were impressed by this recipe. If you have chicken stock, butternut squash, goat cheese, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. It is brought to you by Foodista. Overall, this recipe earns a <b>super spoonacular score of 95%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/5-ingredient-butternut-squash-arugula-and-goat-cheese-pasta-948248">5-Ingredient Butternut Squash, Arugulan and Goat Cheese Pasta</a>, <a href="https://spoonacular.com/recipes/5-ingredient-butternut-squash-arugula-and-goat-cheese-pasta-678878">5-Ingredient Butternut Squash, Arugulan and Goat Cheese Pasta</a>, and <a href="https://spoonacular.com/recipes/butternut-squash-arugula-and-roasted-garlic-goat-cheese-tartine-616411">Butternut Squash, Arugula, and Roasted Garlic Goat Cheese Tartine</a>.',
    cuisines: [],
    dishTypes: [],
    diets: [ 'gluten free', 'lacto ovo vegetarian' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/butternut-squash-arugula-and-goat-cheese-quinoa-636608'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 7,
    gaps: 'no',
    preparationMinutes: 5,
    cookingMinutes: 480,
    aggregateLikes: 2182,
    healthScore: 27,
    creditsText: 'Jen West',
    sourceName: 'Pink When',
    pricePerServing: 141.43,
    id: 715391,
    title: 'Slow Cooker Chicken Taco Soup',
    readyInMinutes: 485,
    servings: 6,
    sourceUrl: 'http://www.pinkwhen.com/slow-cooker-chicken-taco-soup-recipe/',
    image: 'https://spoonacular.com/recipeImages/715391-312x231.jpg',
    imageType: 'jpg',
    summary: 'Slow Cooker Chicken Taco Soup might be just the main course you are searching for. This recipe serves 6 and costs $1.41 per serving. Watching your figure? This gluten free and dairy free recipe has <b>312 calories</b>, <b>24g of protein</b>, and <b>4g of fat</b> per serving. This recipe from Pink When has 2179 fans. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. If you have beans, tomatoes, chili beans, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes around <b>8 hours and 5 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 95%</b>. This score is amazing. Try <a href="https://spoonacular.com/recipes/slow-cooker-chicken-taco-soup-715058">Slow Cooker Chicken Taco Soup</a>, <a href="https://spoonacular.com/recipes/slow-cooker-chicken-taco-soup-927290">Slow Cooker Chicken Taco Soup</a>, and <a href="https://spoonacular.com/recipes/slow-cooker-beef-or-chicken-taco-soup-626944">Slow Cooker Beef or Chicken Taco Soup</a> for similar recipes.',
    cuisines: [ 'Mexican' ],
    dishTypes: [ 'soup' ],
    diets: [ 'gluten free', 'dairy free' ],
    occasions: [ 'fall', 'winter' ],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/slow-cooker-chicken-taco-soup-715391'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 4,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 19,
    healthScore: 61,
    creditsText: 'Afrolems',
    license: 'CC BY 4.0',
    sourceName: 'Afrolems',
    pricePerServing: 366.65,
    id: 716330,
    title: 'Chicken and Mango Skewer',
    readyInMinutes: 45,
    servings: 1,
    sourceUrl: 'http://www.afrolems.com/2013/03/29/easter-special-chicken-and-mango-skewer/',
    image: 'https://spoonacular.com/recipeImages/716330-312x231.jpg',
    imageType: 'jpg',
    summary: 'Chicken and Mango Skewer might be just the main course you are searching for. This gluten free, dairy free, and whole 30 recipe serves 1 and costs <b>$3.67 per serving</b>. One serving contains <b>420 calories</b>, <b>30g of protein</b>, and <b>7g of fat</b>. A couple people made this recipe, and 19 would say it hit the spot. A mixture of chicken breast, chicken stock cube, mangos, and a handful of other ingredients are all it takes to make this recipe so tasty. To use up the vegetable cooking oil you could follow this main course with the <a href="https://spoonacular.com/recipes/banana-bread-no7-523115">Banana Bread no.7</a> as a dessert. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 95%</b>. This score is outstanding. Try <a href="https://spoonacular.com/recipes/grilled-chicken-caesar-on-a-skewer-338979">Grilled Chicken Caesar on a Skewer</a>, <a href="https://spoonacular.com/recipes/thai-chicken-skewer-appetizers-with-sweet-and-spicy-chili-sauce-621582">Thai Chicken Skewer Appetizers with Sweet and Spicy Chili Sauce</a>, and <a href="https://spoonacular.com/recipes/caprese-skewer-301739">Caprese Skewer</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'gluten free', 'dairy free', 'whole 30' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/chicken-and-mango-skewer-716330'
  }
  {
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 3,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 18,
    healthScore: 52,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 66.47,
    id: 636230,
    title: 'Broccoli with cheese soup',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/ZYJG37NG/broccoli-with-cheese-soup',
    image: 'https://spoonacular.com/recipeImages/636230-312x231.jpg',
    imageType: 'jpg',
    summary: 'Broccoli with cheese soup requires around <b>around 45 minutes</b> from start to finish. For <b>66 cents per serving</b>, 
  this recipe <b>covers 18%</b> of your daily requirements of vitamins and minerals. Watching your figure? This lacto ovo vegetarian recipe has <b>121 calories</b>, <b>7g of protein</b>, and <b>5g of fat</b> per serving. This recipe serves 4. This recipe from Foodista requires broccoli florets, swiss chesee, milk, and feta cheese. It works well as a side dish. 18 people were impressed by this recipe. 
  It can be enjoyed any time, but it is especially good for <b>Autumn</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 95%</b>, which is tremendous. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/broccoli-cheese-soup-627441">Broccoli Cheese Soup</a>, <a href="https://spoonacular.com/recipes/broccoli-cheese-soup-516445">Broccoli Cheese Soup</a>, and <a href="https://spoonacular.com/recipes/broccoli-cheese-soup-973016">Broccoli Cheese Soup</a>.',
    cuisines: [],
    dishTypes: [ 'side dish' ],
    diets: [ 'lacto ovo vegetarian' ],
    occasions: [ 'fall', 'winter' ],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/broccoli-with-cheese-soup-636230'
  }
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 9,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 100,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 111.47,
    id: 652393,
    title: 'Moosewood Lentil Soup',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://www.foodista.com/recipe/TNZ67L5Y/moosewood-lentil-soup',
    image: 'https://spoonacular.com/recipeImages/652393-312x231.jpg',
    imageType: 'jpg',
    summary: 'Moosewood Lentil Soup is a <b>gluten free and vegan</b> main course. One serving contains <b>423 calories</b>, <b>27g of protein</b>, and <b>4g of fat</b>. For <b>$1.2 per serving</b>, this recipe <b>covers 38%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista has 2 fans. It is perfect for <b>Autumn</b>. Head to the store and pick up pepper, tomatoes, celery, and a few other things to make it today. To use up the salt you could follow this main course with the <a href="https://spoonacular.com/recipes/apple-turnovers-recipe-48175">Apple Turnovers Recipe</a> as a dessert. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 94%</b>. This score is spectacular. Similar recipes include <a href="https://spoonacular.com/recipes/moosewood-mushroom-barley-soup-143909">Moosewood Mushroom Barley Soup!</a>, <a href="https://spoonacular.com/recipes/hungarian-mushroom-soup-from-the-moosewood-cookbook-143242">Hungarian Mushroom Soup, from the Moosewood Cookbook</a>, and <a href="https://spoonacular.com/recipes/moosewood-restaurant-almost-fat-free-cornbread-104631">Moosewood Restaurant Almost Fat-Free Cornbread</a>.',
    cuisines: [],
    dishTypes: [ 'soup' ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [ 'fall', 'winter' ],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/moosewood-lentil-soup-652393'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 29,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 11,
    healthScore: 72,
    creditsText: 'foodista.com',
    sourceName: 'foodista.com',
    pricePerServing: 499.01,
    id: 640117,
    title: 'Corn-Crusted Fish Tacos With Jalapeno-Lime Sauce and Spicy Black Beans',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.foodista.com/recipe/T5S32FWS/corn-crusted-fish-tacos-with-jalapeno-lime-sauce-and-spicy-black-beans',        
    image: 'https://spoonacular.com/recipeImages/640117-312x231.jpg',
    imageType: 'jpg',
    summary: `You can never have too many main course recipes, so give Corn-Crusted Fish Tacos With Jalapeno-Lime Sauce and Spicy Black 
  Beans a try. This recipe makes 4 servings with <b>1112 calories</b>, <b>57g of protein</b>, and <b>54g of fat</b> each. For <b>$4.9 per serving</b>, this recipe <b>covers 50%</b> of your daily requirements of vitamins and minerals. 11 person have made this recipe and 
  would make it again. It is a good option if you're following a <b>gluten free and pescatarian</b> diet. A mixture of mayo, tomatoes, cilantro, and a handful of other ingredients are all it takes to make this recipe so flavorful. To use up the olive oil you could follow this main course with the <a href="https://spoonacular.com/recipes/sauteed-banana-granola-and-yogurt-parfait-624619">Sauteed Banana, Granolan and Yogurt Parfait</a> as a dessert. This recipe is typical of Mexican cuisine. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 94%</b>. This score is super. Similar recipes include <a href="https://spoonacular.com/recipes/corn-crusted-fish-tacos-with-jalapeno-lime-sauce-and-spicy-black-beans-552017">Corn-Crusted Fish Tacos with Jalapeno-Lime Sauce and Spicy Black Beans</a>, <a href="https://spoonacular.com/recipes/corn-crusted-fish-tacos-with-jalapeno-lime-sauce-and-spicy-blac-6996">Corn-crusted Fish Tacos With Jalapeno-lime Sauce And Spicy Blac</a>, and <a href="https://spoonacular.com/recipes/fish-tacos-with-jalapeno-lime-sauce-801518">Fish Tacos with Jalapeno Lime Sauce</a>.`,
    cuisines: [ 'Mexican' ],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'gluten free', 'pescatarian' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/corn-crusted-fish-tacos-with-jalapeno-lime-sauce-and-spicy-black-beans-640117'       
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 5,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3,
    healthScore: 99,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 306.12,
    id: 644826,
    title: 'Gluten Free Dairy Free Sugar Free Chinese Chicken Salad',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://www.foodista.com/recipe/ZSNGMXBF/gluten-free-dairy-free-sugar-free-chinese-chicken-salad',
    image: 'https://spoonacular.com/recipeImages/644826-312x231.jpg',
    imageType: 'jpg',
    summary: `The recipe Gluten Free Dairy Free Sugar Free Chinese Chicken Salad could satisfy your Chinese craving in around <b>45 minutes</b>. One serving contains <b>351 calories</b>, <b>31g of protein</b>, and <b>15g of fat</b>. For <b>$3.06 per serving</b>, this recipe <b>covers 32%</b> of your daily requirements of vitamins and minerals. It works well as a pretty expensive main course. A mixture of extra virgin olive oil, xylitol, juice of 1 mandarin (cut crosswise then tablespoon into jar over a strainer), and a handful of other ingredients are all it takes to make this recipe so flavorful. To use up the white sesame seeds you could follow this main course 
  with the <a href="https://spoonacular.com/recipes/sesame-banana-bread-80347">Sesame Banana Bread</a> as a dessert. It is a good option if you're following a <b>gluten free and dairy free</b> diet. 1 person were impressed by this recipe. All things considered, we decided this recipe <b>deserves a spoonacular score of 93%</b>. This score is outstanding. Try <a href="https://spoonacular.com/recipes/thousand-island-dressing-gluten-free-corn-free-dairy-free-soy-free-nut-free-gum-free-and-refined-sugar-free-512186">Thousand Island Dressing (Gluten-Free, Corn-Free, Dairy-Free, Soy-Free, Nut-Free, Gum-Free and Refined Sugar-Free)</a>, <a href="https://spoonacular.com/recipes/everything-free-cookies-dairy-free-gluten-free-egg-free-nut-free-sugar-free-728610">Everything-Free Cookies (dairy-free, gluten-free, egg-free, nut-free, & sugar-free)</a>, and <a href="https://spoonacular.com/recipes/gluten-free-vegan-walnut-and-oat-brownies-vegan-gluten-free-grain-free-flourless-dairy-free-no-refined-sugar-617963">Gluten-Free Vegan Walnut and Oat Brownies (Vegan, Gluten-Free, Grain-Free, Flourless, Dairy-Free, No Refined Sugar)</a> for similar recipes.`,
    cuisines: [ 'Chinese', 'Asian' ],
    dishTypes: [ 'salad' ],
    diets: [ 'gluten free', 'dairy free' ],
    occasions: [],
    analyzedInstructions: [
      { name: '', steps: [Array] },
      {
        name: 'Add all the ingredients into a large serving bowl.For the dressing',
        steps: [Array]
      }
    ],
    spoonacularSourceUrl: 'https://spoonacular.com/gluten-free-dairy-free-sugar-free-chinese-chicken-salad-644826'
  }
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 6,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3,
    healthScore: 100,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 127.66,
    id: 642085,
    title: 'Easy Roasted Vegetables',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/RFJQ5QGF/easy-roasted-vegetables',
    image: 'https://spoonacular.com/recipeImages/642085-312x231.jpg',
    imageType: 'jpg',
    summary: 'Easy Roasted Vegetables is a <b>gluten free, dairy free, lacto ovo vegetarian, and whole 30</b> recipe with 4 servings. One serving contains <b>297 calories</b>, <b>11g of protein</b>, and <b>4g of fat</b>. For <b>$1.28 per serving</b>, this recipe <b>covers 33%</b> of your daily requirements of vitamins and minerals. This recipe is liked by 2 foodies and cooks. Not a lot of people really liked this side dish. If you have butternut squash, salt & pepper, paprika, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. From preparation to the plate, this recipe takes about <b>about 45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 95%</b>. This score is spectacular. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/easy-roasted-vegetables-379674">Easy Roasted Vegetables</a>, <a href="https://spoonacular.com/recipes/easy-roasted-summer-vegetables-590293">Easy Roasted Summer Vegetables</a>, and <a href="https://spoonacular.com/recipes/easy-herb-roasted-chicken-vegetables-587141">Easy Herb-Roasted Chicken & Vegetables</a>.',
    cuisines: [],
    dishTypes: [ 'side dish' ],
    diets: [
      'gluten free',
      'dairy free',
      'lacto ovo vegetarian',
      'whole 30',
      'vegan'
    ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/easy-roasted-vegetables-642085'
  }
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 4,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3,
    healthScore: 94,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 185.86,
    id: 662968,
    title: 'Tempered Spicy Potatoes',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'http://www.foodista.com/recipe/CQMTFJRH/tempered-spicy-potatoes',
    image: 'https://spoonacular.com/recipeImages/662968-312x231.jpg',
    imageType: 'jpg',
    summary: 'Need a <b>gluten free, whole 30, and vegan side dish</b>? Tempered Spicy Potatoes could be an outstanding recipe to try. This recipe makes 4 servings with <b>132 calories</b>, <b>5g of protein</b>, and <b>1g of fat</b> each. For <b>$1.79 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. A mixture of salt, curry leaves, chilli flakes, and 
  a handful of other ingredients are all it takes to make this recipe so tasty. 3 people have made this recipe and would make it again. 
  From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves 
  a spoonacular score of 82%</b>. This score is super. Try <a href="https://spoonacular.com/recipes/butter-dal-fry-tempered-yellow-lentils-33618">Butter Dal Fry - Tempered Yellow Lentils</a>, <a href="https://spoonacular.com/recipes/spicy-potatoes-218811">Spicy potatoes</a>, and <a href="https://spoonacular.com/recipes/spicy-potatoes-43778">Spicy Potatoes</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'side dish' ],
    diets: [
      'gluten free',
      'dairy free',
      'lacto ovo vegetarian',
      'whole 30',
      'vegan'
    ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/tempered-spicy-potatoes-662968'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 3,
    healthScore: 100,
    creditsText: 'foodista.com',
    sourceName: 'foodista.com',
    pricePerServing: 354.86,
    id: 659109,
    title: 'Salmon Quinoa Risotto',
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: 'https://www.foodista.com/recipe/KH5STR7N/salmon-quinoa-risotto',
    image: 'https://spoonacular.com/recipeImages/659109-312x231.jpg',
    imageType: 'jpg',
    summary: 'Salmon Quinoa Risotto is a <b>gluten free, dairy free, and pescatarian</b> recipe with 4 servings. One portion of this dish contains approximately <b>26g of protein</b>, <b>19g of fat</b>, and a total of <b>439 calories</b>. For <b>$3.55 per serving</b>, this recipe <b>covers 42%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista requires quinoa, onion, vegetable stock, and garlic cloves. 3 people found this recipe to be tasty and satisfying. From preparation to the plate, this recipe takes about <b>about 45 minutes</b>. Not a lot of people really liked this Mediterranean dish. It works well as a main course. Taking all factors into account, this recipe <b>earns a spoonacular score of 95%</b>, which is spectacular. Try <a href="https://spoonacular.com/recipes/quinoa-risotto-with-salmon-and-kale-15276">Quinoa Risotto With Salmon And Kale</a>, <a href="https://spoonacular.com/recipes/quinoa-risotto-36052">Quinoa Risotto</a>, and <a href="https://spoonacular.com/recipes/quinoa-risotto-472468">Quinoa Risotto</a> for 
  similar recipes.',
    cuisines: [ 'Mediterranean', 'Italian', 'European' ],
    dishTypes: [ 'side dish', 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'gluten free', 'dairy free', 'pescatarian' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/salmon-quinoa-risotto-659109'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 5,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 10,
    healthScore: 72,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 49.64,
    id: 646738,
    title: "Herbivoracious' White Bean and Kale Soup",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'https://www.foodista.com/recipe/YX5XP75N/herbivoracious-white-bean-and-kale-soup',
    image: 'https://spoonacular.com/recipeImages/646738-312x231.jpg',
    imageType: 'jpg',
    summary: `Herbivoracious' White Bean and Kale Soup could be just the <b>gluten free</b> recipe you've been looking for. For <b>50 cents per serving</b>, you get a soup that serves 6. One serving contains <b>195 calories</b>, <b>7g of protein</b>, and <b>10g of fat</b>. 10 people have made this recipe and would make it again. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. 
  Head to the store and pick up rosemary leaves, bay leaves, carrot, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. It is brought to you by Foodista. With a spoonacular <b>score of 95%</b>, this dish is excellent. <a href="https://spoonacular.com/recipes/white-bean-kale-soup-709577">White Bean Kale Soup</a>, <a href="https://spoonacular.com/recipes/white-bean-and-kale-soup-759641">White Bean and Kale Soup</a>, and <a href="https://spoonacular.com/recipes/white-bean-and-kale-soup-15247">White Bean And Kale Soup</a> are very similar to this recipe.`,
    cuisines: [],
    dishTypes: [ 'soup' ],
    diets: [ 'gluten free' ],
    occasions: [ 'fall', 'winter' ],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/herbivoracious-white-bean-and-kale-soup-646738'
  }
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 2,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 10,
    healthScore: 63,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 99.12,
    id: 633221,
    title: 'Baby Beet Salad',
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: 'http://www.foodista.com/recipe/NNKTTWLH/baby-beet-salad',
    image: 'https://spoonacular.com/recipeImages/633221-312x231.jpg',
    imageType: 'jpg',
    summary: 'Baby Beet Salad might be just the side dish you are searching for. One serving contains <b>133 calories</b>, <b>3g of protein</b>, and <b>7g of fat</b>. This caveman, gluten free, primal, and whole 30 recipe serves 6 and costs <b>62 cents per serving</b>. 
  10 people were impressed by this recipe. From preparation to the plate, this recipe takes about <b>45 minutes</b>. If you have salt, red-wine vinegar, olive oil, and a few other ingredients on hand, you can make it. All things considered, we decided this recipe <b>deserves a spoonacular score of 75%</b>. This score is pretty good. Try <a href="https://spoonacular.com/recipes/roasted-baby-beet-salad-9168">Roasted Baby Beet Salad</a>, <a href="https://spoonacular.com/recipes/baby-spinach-and-roasted-beet-salad-9533">Baby Spinach And Roasted Beet Salad</a>, and <a href="https://spoonacular.com/recipes/baby-beet-salad-with-feta-walnuts-arugula-8713">Baby Beet Salad 
  With Feta, Walnuts & Arugula</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'salad' ],
    diets: [
      'gluten free',
      'dairy free',
      'paleolithic',
      'lacto ovo vegetarian',
      'primal',
      'whole 30',
      'vegan'
    ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/baby-beet-salad-633221'
  }
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 9,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 7,
    healthScore: 100,
    creditsText: 'foodista.com',
    sourceName: 'foodista.com',
    pricePerServing: 516.03,
    id: 659135,
    title: 'Salmon with roasted vegetables',
    readyInMinutes: 45,
    servings: 2,
    sourceUrl: 'https://www.foodista.com/recipe/7TTSVX56/salmon-with-roasted-vegetables',
    image: 'https://spoonacular.com/recipeImages/659135-312x231.jpg',
    imageType: 'jpg',
    summary: `Salmon with roasted vegetables is a main course that serves 2. One portion of this dish contains around <b>39g of protein</b>, <b>18g of fat</b>, and a total of <b>473 calories</b>. For <b>$5.16 per serving</b>, this recipe <b>covers 46%</b> of your daily 
  requirements of vitamins and minerals. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. Only a few people made this recipe, and 7 would say it hit the spot. It is a good option if you're 
  following a <b>gluten free, dairy free, whole 30, and pescatarian</b> diet. A mixture of rosemary and thyme, onion, lemon juice, and a handful of other ingredients are all it takes to make this recipe so scrumptious. With a spoonacular <b>score of 95%</b>, this dish is tremendous. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/roasted-salmon-vegetables-36765">Roasted Salmon & Vegetables</a>, <a href="https://spoonacular.com/recipes/salmon-with-roasted-vegetables-84853">Salmon With Roasted Vegetables</a>, and <a href="https://spoonacular.com/recipes/roasted-salmon-and-vegetables-176441">Roasted Salmon and Vegetables</a>.`,
    cuisines: [],
    dishTypes: [ 'lunch', 'main course', 'main dish', 'dinner' ],
    diets: [ 'gluten free', 'dairy free', 'whole 30', 'pescatarian' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/salmon-with-roasted-vegetables-659135'
  }
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 4,
    gaps: 'no',
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 87,
    creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
    license: 'CC BY 3.0',
    sourceName: 'Foodista',
    pricePerServing: 42.38,
    id: 647016,
    title: 'HomeMade Hashbrowns with Spinach and Carrots',
    readyInMinutes: 35,
    servings: 3,
    sourceUrl: 'http://www.foodista.com/recipe/WBDJ57G8/homemade-hashbrowns-with-spinach-and-carrots',
    image: 'https://spoonacular.com/recipeImages/647016-312x231.jpg',
    imageType: 'jpg',
    summary: 'You can never have too many side dish recipes, so give HomeMade Hashbrowns with Spinach and Carrots a try. This recipe serves 3 and costs 42 cents per serving. Watching your figure? This gluten free and vegan recipe has <b>153 calories</b>, <b>6g of protein</b>, and <b>0g of fat</b> per serving. Only a few people made this recipe, and 1 would say it hit the spot. If you have salt, chilli powder, cornflour, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>35 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 93%</b>. This score is awesome. Try <a 
  href="https://spoonacular.com/recipes/hashbrowns-spinach-and-tomato-pie-566553">Hashbrowns, Spinach and Tomato Pie</a>, <a href="https://spoonacular.com/recipes/cheesy-spinach-and-egg-hashbrowns-skillet-176202">Cheesy Spinach and Egg Hashbrowns Skillet</a>, and <a href="https://spoonacular.com/recipes/carrots-artichokes-hearts-and-spinach-13978">Carrots, Artichokes Hearts And Spinach</a> for similar recipes.',
    cuisines: [],
    dishTypes: [ 'side dish' ],
    diets: [ 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan' ],
    occasions: [],
    analyzedInstructions: [ { name: '', steps: [Array] } ],
    spoonacularSourceUrl: 'https://spoonacular.com/homemade-hashbrowns-with-spinach-and-carrots-647016'
  }