
export const GET_RECIPE_BY_NAME = 'GET_RECIPE_BY_NAME' ;
export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE' ;
export const ORDER_BY_HEALTHSCORE_ASC = 'ORDER_BY_HEALTHSCORE_ASC' ;
export const ORDER_BY_HEALTHSCORE_DESC = 'ORDER_BY_HEALTHSCORE_DESC' ;
export const ORDER_BY_AZ = 'ORDER_BY_AZ' ;
export const ORDER_BY_ZA = 'ORDER_BY_ZA' ;
export const FILTER_BY_DIET = 'FILTER_BY_DIET' ;
export const REMOVE_FILTER = 'REMOVE_FILTER' ;
export const CLEAN_DETAIL = 'CLEAN_DETAIL' ;




