
export const GET_RECIPE_BY_NAME = 'GET_RECIPE_BY_NAME' ;
export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE' ;
export const ORDER_BY_HEALTHSCORE_ASC = 'ORDER_BY_HEALTHSCORE_ASC' ;
export const ORDER_BY_HEALTHSCORE_DESC = 'ORDER_BY_HEALTHSCORE_DESC' ;
export const ORDER_BY_AZ_ASC = 'ORDER_BY_AZ_ASC' ;
export const ORDER_BY_AZ_DESC = 'ORDER_BY_AZ_DESC' ;
export const FILTER_BY_DIET = 'FILTER_BY_DIET' ;



